#!/usr/bin/env ansible-playbook
- hosts: localhost
  vars_files:
    - defaults/main.yml
    - vars/main.yml

  roles:
    - role: jimmy01240397.nodejs 
    - role: jimmy01240397.letsencrypt
      emails: "{{ emails }}"
      certs: "{{ certs }}"
    - role: nginxinc.nginx

  tasks:
    - name: include main task
      include: tasks/main.yml
  
  handlers:
    - include: handlers/main.yml
