- name: Init os var
  include_vars: "vars/{{ ansible_system | lower }}.yml"

- name: Copy judge frondend directory
  copy:
    src: "src/"
    dest: "{{ tmpdir }}"
  become: true

- name: Install npm package
  command:
    cmd: npm install --legacy-peer-deps
    chdir: "{{ tmpdir }}"
  become: true

- name: Build npm
  command:
    cmd: npm run build
    chdir: "{{ tmpdir }}"
  become: true

- name: Copy dist to webdir
  copy:
    remote_src: true
    src: "{{ tmpdir }}/dist/"
    dest: "{{ webdir }}"
  become: true

- name: Remove tmp
  file: 
    state: absent
    path: "{{ tmpdir }}"
  ignore_errors: true

- name: Check letsencrypt config exist
  stat:
    path: "/etc/letsencrypt/options-ssl-nginx.conf"
  become: true
  register: config

- name: Copy letsencrypt config
  template:
    src: "templates/options-ssl-nginx.conf"
    dest: "/etc/letsencrypt/options-ssl-nginx.conf"
  when: not config.stat.exists
  become: true
  notify: Start nginx

- name: Check nginx config exist
  stat:
    path: "{{ nginxdir }}/conf.d/nasa.conf"
  become: true
  register: config

- name: Copy nginx config
  template:
    src: "templates/nasa.conf"
    dest: "{{ nginxdir }}/conf.d/nasa.conf"
  when: not config.stat.exists
  become: true
  notify: Start nginx
